name: Lint Python
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to v4
      - name: Setup Python
        uses: actions/setup-python@v5  # Updated to v5
        with:
          python-version: '3.11'  # Explicitly set a stable Python version

      - name: Install dependencies
        run: |  # Use | for multi-line run steps
          python -m pip install --upgrade pip
          python -m pip install flake8 isort nbqa black~=24.10 # Install black here too

      - name: Run black code style check
        uses: psf/black@stable
        with:
          options: "--check --diff"  # Check and show diffs
          version: "~24.10"  # Use a recent version of black
          src: "./"  # Specify source directory

      - name: Run Flake8 Linter
        run: flake8 .

      - name: Run isort
        run: isort --check-only --profile black --diff .

      - name: Run flake8 on notebooks
        run: nbqa flake8 .